<?php
namespace phpDocumentor\Scrybe\Converter\Metadata;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-23 at 16:28:56.
 */
class TableOfContentsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TableOfContents
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TableOfContents;
    }

    /**
     * @covers phpDocumentor\Scrybe\Converter\Metadata\TableOfContents::getHierarchical
     */
    public function testGetHierarchical()
    {
        // setup
        $h1 = new TableOfContents\Entry();
        $h1->setLevel(1);
        $h1->setName('h1');

        $h2 = clone $h1;
        $h2->setLevel(2);
        $h2->setName('h2');

        $h3 = clone $h2;
        $h3->setLevel(3);
        $h3->setName('h3');

        $h1_2 = clone $h1;
        $h1_2->setName('h1_2');

        $h1_3 = clone $h1;
        $h1_3->setName('h1_3');

        $h2_3 = clone $h2;
        $h2_3->setName('h2_3');

        $this->object[] = $h1;
        $this->object[] = $h2;
        $this->object[] = $h3;
        $this->object[] = $h1_2;
        $this->object[] = $h1_3;
        $this->object[] = $h2_3;

        // test
        $result = $this->object->getHierarchical();

        // assert
        $this->assertSame($h1, $result[0]['entry']);
        $this->assertSame($h2, $result[0]['children'][0]['entry']);
        $this->assertSame($h3, $result[0]['children'][0]['children'][0]['entry']);
        $this->assertSame($h1_2, $result[1]['entry']);
        $this->assertSame($h1_3, $result[2]['entry']);
        $this->assertSame($h2_3, $result[2]['children'][0]['entry']);
    }
}
